### ISSUE TITLE
C01 only has ex06

### ISSUE THREAD

**Issue by bacitoto** [MiguelCo01/42Lisboa_Piscine_Tester#1]
Missing all exercises except ex06

 Also my ex06 passed moulinette but I'm getting [segfault] on last test:

TEST`(test_lenght(0, 0)`);

your test_ft
```
int	ft_strlen(char *str);


void	test_lenght(char *str, int expected)
{
	int actual = ft_strlen(str);
	if (actual != expected)
	{
		printf("Expected: %d, Actual: %d\n", expected, actual);
	}
	else
	{
		printf("Ok\n");
	}
}
```

my ft (passed moulinette)
```

int	ft_strlen(char *str)
{
	int	i;

	i = 0;
	while (str[i] != '\0')
	{
		i++;
	}
	return (i);
}
```

**Comment by MiguelCo01** [comment]
I need to add the remaining ex to C01

The last test tries to get the length of a string that is a NULL pointer. 
It should not be there since at this stage there is not need to test for this.

Maybe it will be corrected.
